; ops.ls
; Run:
;   ./lambdascript -q ops.ls
;
; Expected:
;   True

SHOW = \b.b True False

TEST_AND = ~ (TRUE ^ FALSE)
TEST_OR = TRUE v FALSE
TEST_NOT = ~ FALSE
TEST_IMP = FALSE -> TRUE
TEST_IFF = ~ (TRUE <-> FALSE)

TEST_U_AND = TRUE ∧ TRUE
TEST_U_IMP = FALSE → FALSE
TEST_U_IFF = TRUE ↔ TRUE
TEST_U_NOT = ¬ TRUE <-> FALSE

TEST_PREC_AND_OR = TRUE v FALSE ^ FALSE
TEST_PREC_IFF_IMP = ~ (FALSE <-> FALSE -> TRUE)

ALL = TEST_AND ^ TEST_OR ^ TEST_NOT ^ TEST_IMP ^ TEST_IFF ^ TEST_U_AND ^ TEST_U_IMP ^ TEST_U_IFF ^ TEST_U_NOT ^ TEST_PREC_AND_OR ^ TEST_PREC_IFF_IMP

SHOW ALL